version: "3.8"

services:

    the-intention-app-api:

        container_name: the-intention-app-api
        
        image: softwareshinobi/the-intention-app-api

        build: 

            context: .

            dockerfile: Dockerfile

        restart: always

        ports:

            - "8888:8888"
